//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorDeConsumos.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestorDeConsumos.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en el registro de la transacción..
        /// </summary>
        internal static string Error_ErrorDesconocido {
            get {
                return ResourceManager.GetString("Error_ErrorDesconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los parámetros provistos no son válidos..
        /// </summary>
        internal static string Error_ParametrosInvalidos {
            get {
                return ResourceManager.GetString("Error_ParametrosInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe especificar los datos del consumo (consumo == null)..
        /// </summary>
        internal static string InvalidParam_ConsumoNullOrEmpty {
            get {
                return ResourceManager.GetString("InvalidParam_ConsumoNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha especificada no es válida..
        /// </summary>
        internal static string InvalidParam_FechaNoValida {
            get {
                return ResourceManager.GetString("InvalidParam_FechaNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe especificar el ID de tarjeta de HF..
        /// </summary>
        internal static string InvalidParam_IdTarjetaNoIdentificado {
            get {
                return ResourceManager.GetString("InvalidParam_IdTarjetaNoIdentificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe especificar el IMEI..
        /// </summary>
        internal static string InvalidParam_ImeiNoEspecificado {
            get {
                return ResourceManager.GetString("InvalidParam_ImeiNoEspecificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de consumo o el monto especificado no son válidos..
        /// </summary>
        internal static string InvalidParam_TipoConsumoInvalido {
            get {
                return ResourceManager.GetString("InvalidParam_TipoConsumoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe especificar el tipo de consumo..
        /// </summary>
        internal static string InvalidParam_TipoConsumoNoEspecificado {
            get {
                return ResourceManager.GetString("InvalidParam_TipoConsumoNoEspecificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo registrar el consumo: {0} - {1}.
        /// </summary>
        internal static string Log_BadRequest {
            get {
                return ResourceManager.GetString("Log_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumo Registrado: {0}.
        /// </summary>
        internal static string Log_ConsumoRegistrado {
            get {
                return ResourceManager.GetString("Log_ConsumoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error desconocido: No se pudo registrar el consumo: {0} - {1}.
        /// </summary>
        internal static string Log_ErrorDesconocido {
            get {
                return ResourceManager.GetString("Log_ErrorDesconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de registro de consumo: {0}.
        /// </summary>
        internal static string Log_InicioRegistroConsumo {
            get {
                return ResourceManager.GetString("Log_InicioRegistroConsumo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros inválidos: {0}.
        /// </summary>
        internal static string Log_ParametrosInvalidos {
            get {
                return ResourceManager.GetString("Log_ParametrosInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string Resultado_Error {
            get {
                return ResourceManager.GetString("Resultado_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Resultado_OK {
            get {
                return ResourceManager.GetString("Resultado_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL.
        /// </summary>
        internal static string TipoConsumo_Almuerzo {
            get {
                return ResourceManager.GetString("TipoConsumo_Almuerzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        internal static string TipoConsumo_CuentaCorriente {
            get {
                return ResourceManager.GetString("TipoConsumo_CuentaCorriente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS.
        /// </summary>
        internal static string TipoConsumo_Desayuno {
            get {
                return ResourceManager.GetString("TipoConsumo_Desayuno", resourceCulture);
            }
        }
    }
}
